# Generated by Django 3.2 on 2022-03-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0007_photo_is_ai_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
