# Generated by Django 3.2 on 2022-04-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0010_alter_tag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='status',
        ),
        migrations.AddField(
            model_name='photo',
            name='match',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
