# Generated by Django 3.2 on 2022-04-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0014_auto_20220413_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='has_tag',
            new_name='has_status',
        ),
    ]
