# Generated by Django 3.2 on 2022-04-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0015_rename_has_tag_photo_has_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='has_status',
        ),
    ]
