# Generated by Django 3.2 on 2022-05-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0016_remove_photo_has_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='full_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
