# Generated by Django 3.2 on 2022-05-03 12:28

from django.db import migrations, models
import photosii.models


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0017_photo_full_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='full_image',
            field=models.ImageField(blank=True, null=True, upload_to=photosii.models.gen_image_filename_full),
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photosii.models.gen_image_filename),
        ),
    ]
