# Generated by Django 3.2 on 2022-05-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0019_auto_20220504_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
