# Generated by Django 3.2 on 2022-05-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosii', '0020_photo_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
